name: boletim-saude-infra

services:
  app:
    container_name: boletim-saude-api
    build: .
    environment:
      - APPLICATION_PROFILE=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/BoletimMedico
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=BoletimMedico
    ports:
      - "5432:5432"
