#VALORES APENAS DE EXEMPLO, NÃO USAR EM PRODUÇÃO!
name: boletim-saude-infra

services:
  app:
    container_name: boletim-saude-api
    image: lucaslemec/boletim-saude:2.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/BoletimSaude
      - API_TOKEN_SECRET=lzl024rRZc
      - USUARIO_LOGIN=admin
      - SENHA_LOGIN=123
    ports:
      - "8080:8080"
    networks:
      - boletim-saude-network
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=BoletimSaude
    ports:
      - "5432:5432"
    volumes:
      - ../docker/data/postgresql:/var/lib/postgresql/data
    networks:
      - boletim-saude-network

  app-frontend:
    container_name: boletim-saude-app
    image: lucaslemec/boletim-saude-app:2.0.1
    environment:
      - NEXTAUTH_SECRET="OFsQ6wuWlBCetNwuME5qus2Zocu23bF0W9d3dZo5hGk="
    ports:
      - "3000:3000"
    networks:
      - boletim-saude-network
    depends_on:
        - app

  nginx:
    container_name: nginx-gateway
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-frontend
    networks:
      - boletim-saude-network
    
networks:
  boletim-saude-network:
    driver: bridge