spring:
  profiles:
    active: ${APPLICATION_PROFILE}

  application:
    name: boletim-saude-api

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api
    port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}